services:
  - type: web
    name: shahd-senior-platform
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: SITE_URL
        value: https://shahd-senior.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WHATSAPP_API_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
        
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
        
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        
    redirects:
      - source: /old-page
        destination: /new-page
        type: 301
    
