services:
  - type: web
    name: freelancer-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SETUP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: freelancer-db
          property: connectionString
      - key: MAIL_USERNAME
        value: your-email@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587

databases:
  - name: freelancer-db
    databaseName: freelancer
    user: freelancer_user
    plan: free
