services:
  - type: web
    name: shahd-senior-platform
    env: static
    buildCommand: echo "Building static site..."
    staticPublishPath: ./
    domains:
      - shahd-senior.onrender.com

    # إعدادات البيئة
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: WHATSAPP_NUMBER
        value: "201234567890"

    # إعدادات الأمان
    headers:
      - path: /*
        headers:
          - name: X-Content-Type-Options
            value: nosniff
          - name: X-Frame-Options
            value: DENY
          - name: X-XSS-Protection
            value: 1; mode=block
          - name: Content-Security-Policy
            value: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src fonts.gstatic.com; img-src 'self' data:

    # إعدادات إعادة التوجيه
    routes:
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /fc25
        destination: /fc25.html
      - type: rewrite
        source: /faq
        destination: /faq.html
      - type: rewrite
        source: /terms
        destination: /terms.html
      - type: rewrite
        source: /contact
        destination: /contact.html

    # إعدادات الضغط
    buildFilter:
      paths:
        - css/**
        - js/**
        - images/**
        - data/**
        - "*.html"
